import { Archivo_Black, Roboto } from 'next/font/google';
import Footer from './components/Footer';

import Header from './components/Header';
import './globals.css';

const archivoBlack = Archivo_Black({
  weight: '400',
  variable: '--font-archivo-black',
});

const roboto = Roboto({
  weight: ['400', '700'],
  variable: '--font-roboto',
});

export const metadata = {
  title: "Oleksandr's Porfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${archivoBlack.variable} ${roboto.variable} scroll-smooth`}
    >
      <body className="font-roboto">
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
