import { Montserrat, Roboto } from 'next/font/google';

import './globals.css';

const montserrat = Montserrat({
  weight: ['400', '600'],
  variable: '--font-montserrat',
});

const roboto = Roboto({
  weight: ['400', '500'],
  variable: '--font-roboto',
});

export const metadata = {
  title: "Sasha's Porfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${roboto.variable} scroll-smooth`}
    >
      <body className="font-roboto">{children}</body>
    </html>
  );
}
